# Generated by Django 5.1.6 on 2025-02-10 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_construccion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monumentos.encargado')),
                ('materiales', models.ManyToManyField(to='monumentos.materialespecifico')),
                ('monumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monumentos.monumento')),
            ],
        ),
    ]
