# Generated by Django 5.1.6 on 2025-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monumentos', '0002_rename_materialespecifico_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumento',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='monumento'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='proyectpo'),
        ),
    ]
